echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > pom.xml
echo "<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">" >> pom.xml
echo "  <modelVersion>4.0.0</modelVersion>" >> pom.xml
echo "  <groupId>a0ece5d6-6eab-4fa2-ab08-b50224debdb0</groupId>" >> pom.xml
echo "  <artifactId>lotto</artifactId>" >> pom.xml
echo "  <version>1.0.0</version>" >> pom.xml
echo "  <packaging>mule-application</packaging>" >> pom.xml
echo "  <name>lotto</name>" >> pom.xml
echo "  <properties>" >> pom.xml
echo "    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>" >> pom.xml
echo "    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>" >> pom.xml
echo "    <app.runtime>4.8.0</app.runtime>" >> pom.xml
echo "    <mule.maven.plugin.version>4.1.1</mule.maven.plugin.version>" >> pom.xml
echo "  </properties>" >> pom.xml
echo "  <build>" >> pom.xml
echo "    <plugins>" >> pom.xml
echo "      <plugin>" >> pom.xml
echo "        <groupId>org.mule.tools.maven</groupId>" >> pom.xml
echo "        <artifactId>mule-maven-plugin</artifactId>" >> pom.xml
echo "        <version>${mule.maven.plugin.version}</version>" >> pom.xml
echo "        <extensions>true</extensions>" >> pom.xml
echo "      </plugin>" >> pom.xml
echo "      <plugin>" >> pom.xml
echo "        <groupId>org.apache.maven.plugins</groupId>" >> pom.xml
echo "        <artifactId>maven-clean-plugin</artifactId>" >> pom.xml
echo "        <version>3.2.0</version>" >> pom.xml
echo "      </plugin>" >> pom.xml
echo "    </plugins>" >> pom.xml
echo "  </build>" >> pom.xml
echo "  <dependencies>" >> pom.xml
echo "    <dependency>" >> pom.xml
echo "      <groupId>org.mule.connectors</groupId>" >> pom.xml
echo "      <artifactId>mule-http-connector</artifactId>" >> pom.xml
echo "      <version>1.9.3</version>" >> pom.xml
echo "      <classifier>mule-plugin</classifier>" >> pom.xml
echo "    </dependency>" >> pom.xml
echo "    <dependency>" >> pom.xml
echo "      <groupId>org.mule.connectors</groupId>" >> pom.xml
echo "      <artifactId>mule-sockets-connector</artifactId>" >> pom.xml
echo "      <version>1.2.4</version>" >> pom.xml
echo "      <classifier>mule-plugin</classifier>" >> pom.xml
echo "    </dependency>" >> pom.xml
echo "  </dependencies>" >> pom.xml
echo "  <repositories>" >> pom.xml
echo "    <repository>" >> pom.xml
echo "      <id>jfrog</id>" >> pom.xml
echo "      <url>https://working-cobra-early.ngrok-free.app/artifactory/mule4-jars/</url>" >> pom.xml
echo "    </repository>" >> pom.xml
echo "    <repository>" >> pom.xml
echo "      <id>Repository</id>" >> pom.xml
echo "      <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/\${project.groupId}/maven</url>" >> pom.xml
echo "    </repository>" >> pom.xml
echo "  </repositories>" >> pom.xml
echo "  <distributionManagement>" >> pom.xml
echo "    <repository>" >> pom.xml
echo "      <id>jfrog</id>" >> pom.xml
echo "      <url>https://working-cobra-early.ngrok-free.app/artifactory/mule4-jars/</url>" >> pom.xml
echo "    </repository>" >> pom.xml
echo "  </distributionManagement>" >> pom.xml
echo "  <parent>" >> pom.xml
echo "    <groupId>a0ece5d6-6eab-4fa2-ab08-b50224debdb0</groupId>" >> pom.xml
echo "    <artifactId>parent-pom</artifactId>" >> pom.xml
echo "    <version>1.0.0</version>" >> pom.xml
echo "    <relativePath>./parent_pom.xml</relativePath>" >> pom.xml
echo "  </parent>" >> pom.xml
echo "</project>" >> pom.xml
